#include "data_loader.h"
#include "inference.h"
#include "model.h"

#include <gtest/gtest.h>

#include <cstdio>
#include <numeric>
#include <string>
#include <vector>

// ============================================================================
// Data Loader Tests — Synthetic IDX Files
// ============================================================================
// These tests use the synthetic MNIST files generated by
// scripts/generate_test_mnist.py in tests/data/

static const std::string TEST_IMAGES = "tests/data/test-images-idx3-ubyte";
static const std::string TEST_LABELS = "tests/data/test-labels-idx1-ubyte";

TEST(DataLoader, LoadImages) {
    Tensor images = load_mnist_images(TEST_IMAGES);

    // 5 synthetic images, each 1x28x28
    EXPECT_EQ(images.shape(), (std::vector<int>{5, 1, 28, 28}));
    EXPECT_EQ(images.num_elements(), 5 * 1 * 28 * 28);
}

TEST(DataLoader, ImagesNormalized) {
    Tensor images = load_mnist_images(TEST_IMAGES);

    // All pixel values should be in [0, 1]
    for (int i = 0; i < images.num_elements(); ++i) {
        EXPECT_GE(images[i], 0.0f) << "Pixel below 0 at index " << i;
        EXPECT_LE(images[i], 1.0f) << "Pixel above 1 at index " << i;
    }
}

TEST(DataLoader, LoadSubsetImages) {
    Tensor images = load_mnist_images(TEST_IMAGES, 2);

    // Should only load 2 of the 5 available
    EXPECT_EQ(images.shape(), (std::vector<int>{2, 1, 28, 28}));
}

TEST(DataLoader, LoadLabels) {
    std::vector<int> labels = load_mnist_labels(TEST_LABELS);

    // 5 synthetic labels: [0, 1, 2, 3, 4]
    EXPECT_EQ(labels.size(), 5u);
    for (int i = 0; i < 5; ++i) {
        EXPECT_EQ(labels[static_cast<size_t>(i)], i);
    }
}

TEST(DataLoader, LoadSubsetLabels) {
    std::vector<int> labels = load_mnist_labels(TEST_LABELS, 3);

    EXPECT_EQ(labels.size(), 3u);
    EXPECT_EQ(labels[0], 0);
    EXPECT_EQ(labels[1], 1);
    EXPECT_EQ(labels[2], 2);
}

TEST(DataLoader, LabelsInRange) {
    std::vector<int> labels = load_mnist_labels(TEST_LABELS);

    for (size_t i = 0; i < labels.size(); ++i) {
        EXPECT_GE(labels[i], 0) << "Label below 0 at index " << i;
        EXPECT_LE(labels[i], 9) << "Label above 9 at index " << i;
    }
}

TEST(DataLoader, NonexistentImageFileThrows) {
    EXPECT_THROW(load_mnist_images("nonexistent_file"), std::runtime_error);
}

TEST(DataLoader, NonexistentLabelFileThrows) {
    EXPECT_THROW(load_mnist_labels("nonexistent_file"), std::runtime_error);
}

// ============================================================================
// End-to-End Pipeline — Full Integration Tests
// ============================================================================

TEST(EndToEnd, InferenceOutputShape) {
    // Xavier model + synthetic input → should produce (N, 10) output
    Model model;
    model.initialize_xavier(42);

    Tensor images = load_mnist_images(TEST_IMAGES, 1);
    Tensor output = cpu_inference(model, images);

    EXPECT_EQ(output.shape(), (std::vector<int>{1, 10}));
}

TEST(EndToEnd, InferenceProducesValidProbabilities) {
    Model model;
    model.initialize_xavier(42);

    Tensor images = load_mnist_images(TEST_IMAGES, 3);

    // Run inference on each image
    for (int i = 0; i < 3; ++i) {
        Tensor single({1, 1, 28, 28});
        int offset = i * 28 * 28;
        for (int p = 0; p < 28 * 28; ++p) {
            single[p] = images[offset + p];
        }

        Tensor output = cpu_inference(model, single);

        // All in [0, 1]
        for (int j = 0; j < 10; ++j) {
            EXPECT_GE(output.at(0, j), 0.0f);
            EXPECT_LE(output.at(0, j), 1.0f);
        }

        // Sum to 1
        float sum = 0.0f;
        for (int j = 0; j < 10; ++j) {
            sum += output.at(0, j);
        }
        EXPECT_NEAR(sum, 1.0f, 1e-5f);
    }
}

TEST(EndToEnd, PredictReturnsValidClasses) {
    Model model;
    model.initialize_xavier(42);

    Tensor images = load_mnist_images(TEST_IMAGES, 5);

    for (int i = 0; i < 5; ++i) {
        Tensor single({1, 1, 28, 28});
        int offset = i * 28 * 28;
        for (int p = 0; p < 28 * 28; ++p) {
            single[p] = images[offset + p];
        }

        std::vector<int> predictions = cpu_predict(model, single);
        EXPECT_EQ(predictions.size(), 1u);
        EXPECT_GE(predictions[0], 0);
        EXPECT_LE(predictions[0], 9);
    }
}

// ============================================================================
// Regression Test — Deterministic Output with Fixed Seed
// ============================================================================

TEST(EndToEnd, DeterministicRegression) {
    // Same seed + same input → must always produce the same output
    // This catches unintentional changes to any layer

    Model model1;
    model1.initialize_xavier(42);
    Model model2;
    model2.initialize_xavier(42);

    Tensor images = load_mnist_images(TEST_IMAGES, 1);

    Tensor out1 = cpu_inference(model1, images);
    Tensor out2 = cpu_inference(model2, images);

    // Outputs should be bit-for-bit identical
    EXPECT_TRUE(out1 == out2);
}

TEST(EndToEnd, SaveLoadProducesSameOutput) {
    // Save model, reload, verify inference matches
    Model original;
    original.initialize_xavier(42);

    std::string filepath = "test_e2e_model.bin";
    original.save(filepath);

    Model loaded;
    loaded.load(filepath);

    Tensor images = load_mnist_images(TEST_IMAGES, 1);

    Tensor out_orig = cpu_inference(original, images);
    Tensor out_load = cpu_inference(loaded, images);

    EXPECT_TRUE(out_orig == out_load);

    std::remove(filepath.c_str());
}

// ============================================================================
// Pipeline Shape Flow Verification
// ============================================================================

TEST(EndToEnd, IntermediateShapeFlow) {
    // Manually step through the pipeline to verify shapes at each stage
    using cnn::conv2d_forward;
    using cnn::dense_forward;
    using cnn::flatten;
    using cnn::maxpool2d_forward;
    using cnn::relu_forward;
    using cnn::softmax_forward;

    Model model;
    model.initialize_xavier(42);

    Tensor x = load_mnist_images(TEST_IMAGES, 1);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 1, 28, 28}));

    // Block 1
    x = conv2d_forward(x, model.conv1_weights, model.conv1_bias, 1, 1);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 8, 28, 28}));

    x = relu_forward(x);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 8, 28, 28}));

    x = maxpool2d_forward(x, 2);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 8, 14, 14}));

    // Block 2
    x = conv2d_forward(x, model.conv2_weights, model.conv2_bias, 1, 1);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 16, 14, 14}));

    x = relu_forward(x);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 16, 14, 14}));

    x = maxpool2d_forward(x, 2);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 16, 7, 7}));

    // Flatten
    x = flatten(x);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 784}));

    // Dense block
    x = dense_forward(x, model.dense1_weights, model.dense1_bias);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 120}));

    x = relu_forward(x);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 120}));

    x = dense_forward(x, model.dense2_weights, model.dense2_bias);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 10}));

    // Softmax
    x = softmax_forward(x);
    EXPECT_EQ(x.shape(), (std::vector<int>{1, 10}));
}
